name: Playwright Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.php'
      - '**.js'
      - 'package.json'
      - 'tests/e2e/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.php'
      - '**.js'
      - 'package.json'
      - 'tests/e2e/**'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start PHP Server
      run: php -S localhost:8000 -t public &
    - name: Run Playwright tests
      run: npx playwright test tests/e2e
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-screenshots
        path: screenshots/
        retention-days: 7
